name: 功能建议
description: 提议改进应用或文档
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 要解决的问题
      description: 目前的使用流程遇到了什么困难？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建议方案
      description: 希望应用如何工作？
    validations:
      required: true
